// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef SNMP_OBJECT_VALUE_ODB_H
#define SNMP_OBJECT_VALUE_ODB_H

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "SnmpObjectValue.hpp"

#include "MonitorHistory_odb.h"
#include "SnmpObject_odb.h"
#include "SnmpObjectType_odb.h"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/session.hxx>
#include <odb/cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // SnmpObjectValue
  //
  template <>
  struct class_traits< ::SnmpObjectValue >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::SnmpObjectValue >
  {
    public:
    typedef ::SnmpObjectValue object_type;
    typedef ::std::shared_ptr< ::SnmpObjectValue > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    odb::pointer_cache_traits<
      pointer_type,
      odb::session >
    pointer_cache_traits;

    typedef
    odb::reference_cache_traits<
      object_type,
      odb::session >
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mssql/version.hxx>
#include <odb/mssql/forward.hxx>
#include <odb/mssql/binding.hxx>
#include <odb/mssql/mssql-types.hxx>
#include <odb/mssql/query.hxx>

namespace odb
{
  // SnmpObjectValue
  //
  template <typename A>
  struct pointer_query_columns< ::SnmpObjectValue, id_mssql, A >
  {
    // snmpObjectValueId
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectValueId_type_;

    static const snmpObjectValueId_type_ snmpObjectValueId;

    // value
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        ::std::string,
        mssql::id_string >::query_type,
      mssql::id_string >
    value_type_;

    static const value_type_ value;

    // snmpObjectFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectFk_type_;

    static const snmpObjectFk_type_ snmpObjectFk;

    // snmpObjectTypeFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectTypeFk_type_;

    static const snmpObjectTypeFk_type_ snmpObjectTypeFk;

    // monitorHistoryFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    monitorHistoryFk_type_;

    static const monitorHistoryFk_type_ monitorHistoryFk;
  };

  template <typename A>
  const typename pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectValueId_type_
  pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectValueId (A::table_name, "[snmpObjectValueId]", 0);

  template <typename A>
  const typename pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::value_type_
  pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::
  value (A::table_name, "[value]", 0, 300);

  template <typename A>
  const typename pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectFk_type_
  pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectFk (A::table_name, "[snmpObjectFk]", 0);

  template <typename A>
  const typename pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectTypeFk_type_
  pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectTypeFk (A::table_name, "[snmpObjectTypeFk]", 0);

  template <typename A>
  const typename pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::monitorHistoryFk_type_
  pointer_query_columns< ::SnmpObjectValue, id_mssql, A >::
  monitorHistoryFk (A::table_name, "[monitorHistoryFk]", 0);

  template <>
  class access::object_traits_impl< ::SnmpObjectValue, id_mssql >:
    public access::object_traits< ::SnmpObjectValue >
  {
    public:
    static const std::size_t batch = 1UL;

    static const bool rowversion = false;

    struct id_image_type
    {
      long long id_value;
      SQLLEN id_size_ind;

      std::size_t version;
    };

    struct image_type
    {
      // snmpObjectValueId_
      //
      long long snmpObjectValueId_value;
      SQLLEN snmpObjectValueId_size_ind;

      // value_
      //
      char value_value[301];
      SQLLEN value_size_ind;

      // snmpObjectFk_
      //
      long long snmpObjectFk_value;
      SQLLEN snmpObjectFk_size_ind;

      // snmpObjectTypeFk_
      //
      long long snmpObjectTypeFk_value;
      SQLLEN snmpObjectTypeFk_size_ind;

      // monitorHistoryFk_
      //
      long long monitorHistoryFk_value;
      SQLLEN monitorHistoryFk_size_ind;

      std::size_t version;

      mssql::change_callback change_callback_;

      mssql::change_callback*
      change_callback ()
      {
        return &change_callback_;
      }
    };

    struct extra_statement_cache_type;

    struct snmpObjectFk_tag;
    struct snmpObjectTypeFk_tag;
    struct monitorHistoryFk_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static void
    bind (mssql::bind*,
          image_type&,
          mssql::statement_kind);

    static void
    bind (mssql::bind*, id_image_type&);

    static void
    init (image_type&,
          const object_type&,
          mssql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mssql::object_statements<object_type> statements_type;

    typedef mssql::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::SnmpObjectValue, id_common >:
    public access::object_traits_impl< ::SnmpObjectValue, id_mssql >
  {
  };

  // SnmpObjectValue
  //
  template <>
  struct alias_traits<
    ::SnmpObject,
    id_mssql,
    access::object_traits_impl< ::SnmpObjectValue, id_mssql >::snmpObjectFk_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::SnmpObjectType,
    id_mssql,
    access::object_traits_impl< ::SnmpObjectValue, id_mssql >::snmpObjectTypeFk_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::MonitorHistory,
    id_mssql,
    access::object_traits_impl< ::SnmpObjectValue, id_mssql >::monitorHistoryFk_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::SnmpObjectValue, id_mssql >
  {
    // snmpObjectFk
    //
    typedef
    odb::alias_traits<
      ::SnmpObject,
      id_mssql,
      access::object_traits_impl< ::SnmpObjectValue, id_mssql >::snmpObjectFk_tag>
    snmpObjectFk_alias_;

    // snmpObjectTypeFk
    //
    typedef
    odb::alias_traits<
      ::SnmpObjectType,
      id_mssql,
      access::object_traits_impl< ::SnmpObjectValue, id_mssql >::snmpObjectTypeFk_tag>
    snmpObjectTypeFk_alias_;

    // monitorHistoryFk
    //
    typedef
    odb::alias_traits<
      ::MonitorHistory,
      id_mssql,
      access::object_traits_impl< ::SnmpObjectValue, id_mssql >::monitorHistoryFk_tag>
    monitorHistoryFk_alias_;
  };

  template <typename A>
  struct query_columns< ::SnmpObjectValue, id_mssql, A >:
    query_columns_base< ::SnmpObjectValue, id_mssql >
  {
    // snmpObjectValueId
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectValueId_type_;

    static const snmpObjectValueId_type_ snmpObjectValueId;

    // value
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        ::std::string,
        mssql::id_string >::query_type,
      mssql::id_string >
    value_type_;

    static const value_type_ value;

    // snmpObjectFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectFk_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::SnmpObject,
        id_mssql,
        snmpObjectFk_alias_ > >
    snmpObjectFk_pointer_type_;

    struct snmpObjectFk_type_: snmpObjectFk_pointer_type_, snmpObjectFk_column_type_
    {
      snmpObjectFk_type_ (const char* t,
                          const char* c,
                          const char* conv,
                          unsigned short p = 0,
                          unsigned short s = 0xFFFF)
        : snmpObjectFk_column_type_ (t, c, conv, p, s)
      {
      }
    };

    static const snmpObjectFk_type_ snmpObjectFk;

    // snmpObjectTypeFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    snmpObjectTypeFk_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::SnmpObjectType,
        id_mssql,
        snmpObjectTypeFk_alias_ > >
    snmpObjectTypeFk_pointer_type_;

    struct snmpObjectTypeFk_type_: snmpObjectTypeFk_pointer_type_, snmpObjectTypeFk_column_type_
    {
      snmpObjectTypeFk_type_ (const char* t,
                              const char* c,
                              const char* conv,
                              unsigned short p = 0,
                              unsigned short s = 0xFFFF)
        : snmpObjectTypeFk_column_type_ (t, c, conv, p, s)
      {
      }
    };

    static const snmpObjectTypeFk_type_ snmpObjectTypeFk;

    // monitorHistoryFk
    //
    typedef
    mssql::query_column<
      mssql::value_traits<
        long unsigned int,
        mssql::id_bigint >::query_type,
      mssql::id_bigint >
    monitorHistoryFk_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::MonitorHistory,
        id_mssql,
        monitorHistoryFk_alias_ > >
    monitorHistoryFk_pointer_type_;

    struct monitorHistoryFk_type_: monitorHistoryFk_pointer_type_, monitorHistoryFk_column_type_
    {
      monitorHistoryFk_type_ (const char* t,
                              const char* c,
                              const char* conv,
                              unsigned short p = 0,
                              unsigned short s = 0xFFFF)
        : monitorHistoryFk_column_type_ (t, c, conv, p, s)
      {
      }
    };

    static const monitorHistoryFk_type_ monitorHistoryFk;
  };

  template <typename A>
  const typename query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectValueId_type_
  query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectValueId (A::table_name, "[snmpObjectValueId]", 0);

  template <typename A>
  const typename query_columns< ::SnmpObjectValue, id_mssql, A >::value_type_
  query_columns< ::SnmpObjectValue, id_mssql, A >::
  value (A::table_name, "[value]", 0, 300);

  template <typename A>
  const typename query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectFk_type_
  query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectFk (A::table_name, "[snmpObjectFk]", 0);

  template <typename A>
  const typename query_columns< ::SnmpObjectValue, id_mssql, A >::snmpObjectTypeFk_type_
  query_columns< ::SnmpObjectValue, id_mssql, A >::
  snmpObjectTypeFk (A::table_name, "[snmpObjectTypeFk]", 0);

  template <typename A>
  const typename query_columns< ::SnmpObjectValue, id_mssql, A >::monitorHistoryFk_type_
  query_columns< ::SnmpObjectValue, id_mssql, A >::
  monitorHistoryFk (A::table_name, "[monitorHistoryFk]", 0);
}

#include "SnmpObjectValue_odb_inline.h"

#include <odb/post.hxx>

#endif // SNMP_OBJECT_VALUE_ODB_H
