-- MySQL Script generated by MySQL Workbench
-- 08/23/16 17:03:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema nemstadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nemstadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nemstadb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `nemstadb` ;

-- -----------------------------------------------------
-- Table `nemstadb`.`NetworkElement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`NetworkElement` (
  `NetworkElementId` INT NOT NULL AUTO_INCREMENT,
  `ElementName` VARCHAR(45) NOT NULL,
  `MacAddress` VARCHAR(45) NOT NULL,
  `IpAddress` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NetworkElementId`),
  UNIQUE INDEX `MacAddress_UNIQUE` (`MacAddress` ASC))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nemstadb`.`SnmpObject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`SnmpObject` (
  `SnmpObjectId` INT NOT NULL AUTO_INCREMENT,
  `Mib` VARCHAR(45) NOT NULL,
  `Oid` VARCHAR(45) NOT NULL,
  `ObjectName` VARCHAR(45) NULL,
  PRIMARY KEY (`SnmpObjectId`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nemstadb`.`ItemizedObject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`ItemizedObject` (
  `ItemizedObjectId` INT NOT NULL AUTO_INCREMENT,
  `NetworkElementFk` INT NOT NULL,
  `SnmpObjectFk` INT NOT NULL,
  PRIMARY KEY (`ItemizedObjectId`, `NetworkElementFk`, `SnmpObjectFk`),
  INDEX `fk_ItemizedObject_NetworkElement_idx` (`NetworkElementFk` ASC),
  INDEX `fk_ItemizedObject_SnmpObject1_idx` (`SnmpObjectFk` ASC),
  CONSTRAINT `fk_ItemizedObject_NetworkElement`
    FOREIGN KEY (`NetworkElementFk`)
    REFERENCES `nemstadb`.`NetworkElement` (`NetworkElementId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItemizedObject_SnmpObject1`
    FOREIGN KEY (`SnmpObjectFk`)
    REFERENCES `nemstadb`.`SnmpObject` (`SnmpObjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nemstadb`.`SnmpObjectValue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`SnmpObjectValue` (
  `SnmpObjectValueId` INT NOT NULL AUTO_INCREMENT,
  `Value` VARCHAR(45) NOT NULL,
  `SnmpObjectFk` INT NOT NULL,
  PRIMARY KEY (`SnmpObjectValueId`, `SnmpObjectFk`),
  INDEX `fk_SnmpObjectValue_SnmpObject1_idx` (`SnmpObjectFk` ASC),
  CONSTRAINT `fk_SnmpObjectValue_SnmpObject1`
    FOREIGN KEY (`SnmpObjectFk`)
    REFERENCES `nemstadb`.`SnmpObject` (`SnmpObjectId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nemstadb`.`MonitorHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`MonitorHistory` (
  `MonitorHistoryId` INT NOT NULL AUTO_INCREMENT,
  `LastUpdate` DATETIME NOT NULL,
  `Note` VARCHAR(45) NULL,
  `SnmpObjectValueFk` INT NOT NULL,
  PRIMARY KEY (`MonitorHistoryId`, `SnmpObjectValueFk`),
  INDEX `fk_MonitorHistory_SnmpObjectValue1_idx` (`SnmpObjectValueFk` ASC),
  CONSTRAINT `fk_MonitorHistory_SnmpObjectValue1`
    FOREIGN KEY (`SnmpObjectValueFk`)
    REFERENCES `nemstadb`.`SnmpObjectValue` (`SnmpObjectValueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `nemstadb`.`SnmpObjectType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nemstadb`.`SnmpObjectType` (
  `SnmpObjectTypeId` INT NOT NULL AUTO_INCREMENT,
  `TypeName` VARCHAR(45) NOT NULL,
  `SnmpObjectValueFk` INT NOT NULL,
  PRIMARY KEY (`SnmpObjectTypeId`, `SnmpObjectValueFk`),
  INDEX `fk_SnmpObjectType_SnmpObjectValue1_idx` (`SnmpObjectValueFk` ASC),
  CONSTRAINT `fk_SnmpObjectType_SnmpObjectValue1`
    FOREIGN KEY (`SnmpObjectValueFk`)
    REFERENCES `nemstadb`.`SnmpObjectValue` (`SnmpObjectValueId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
